# Generated by Django 5.2 on 2025-06-08 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nb_processeurs', models.PositiveIntegerField()),
                ('capacite_memoire', models.PositiveIntegerField(help_text='En Mo')),
                ('capacite_stockage', models.PositiveIntegerField(help_text='En Go')),
            ],
        ),
        migrations.CreateModel(
            name='TypeServeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_lancement', models.DateField()),
                ('espace_memoire_utilise', models.PositiveIntegerField(help_text='En Mo')),
                ('memoire_vive_necessaire', models.PositiveIntegerField(help_text='En Mo')),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.serveur')),
            ],
        ),
        migrations.AddField(
            model_name='serveur',
            name='type_serveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.typeserveur'),
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.application')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.service')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.utilisateur'),
        ),
    ]
